//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SedniceNNV.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Prilozi
    {
        public int SednicaID { get; set; }
        public int RedniBrojPriloga { get; set; }
        public string NazivDokumenta { get; set; }
        public string Poslato { get; set; }
        public Nullable<System.DateTime> DatumSlanja { get; set; }
    
        public virtual Sednice Sednice { get; set; }
    }
}
