//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SedniceNNV.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Prisustvo
    {
        public int SednicaID { get; set; }
        public int ClanID { get; set; }
        public string Prisutan { get; set; }
        public string Opravdano { get; set; }
    
        public virtual Clanovi Clanovi { get; set; }
        public virtual Sednice Sednice { get; set; }
    }
}
