//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SedniceNNV.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Sednice
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Sednice()
        {
            this.Prilozi = new HashSet<Prilozi>();
            this.Prisustvo = new HashSet<Prisustvo>();
        }
    
        public int SednicaID { get; set; }
        public System.DateTime Datum { get; set; }
        public string Vrsta { get; set; }
        public string Ucionica { get; set; }
        public string Zapisnik { get; set; }
        public string Poziv { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Prilozi> Prilozi { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Prisustvo> Prisustvo { get; set; }
    }
}
